# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Air Quality Dataset]
- **Nama:** [Windi Sri Rahayu]
- **Email:** [windyrahayu45@gmail.com]
- **ID Dicoding:** [ayuuwindii]

## Menentukan Pertanyaan Bisnis

- Apa saja polutan utama yang berkontribusi terhadap buruknya kualitas udara di perkotaan?
- Bagaimana kualitas udara berubah seiring dengan kondisi cuaca dari waktu ke waktu?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

df = pd.read_csv('PRSA_Data_Wanliu_20130301-20170228.csv')
print(df.head())

"""**Insight:**
- PM10, SO2, NO2, CO, O3: Beberapa nilai untuk polutan lainnya juga tercatat, dengan beberapa nilai kosong (NaN) pada SO2 dan O3 di beberapa entri. Penting untuk memeriksa frekuensi dan pola kekosongan data ini.
- Suhu tercatat bervariasi antara -2.0 hingga -0.7 °C selama periode ini. Suhu yang rendah ini mungkin berkontribusi pada kondisi udara yang lebih bersih, tetapi dapat mempengaruhi konsentrasi polutan tertentu seperti PM2.5 yang mungkin lebih terperangkap di dekat permukaan dalam suhu yang lebih dingin.
- Data ini mencakup pengukuran yang dilakukan pada jam-jam berbeda, dan pola fluktuasi sepanjang hari dapat memberikan wawasan lebih lanjut. Misalnya, apakah kualitas udara lebih buruk pada jam sibuk ketika lebih banyak kendaraan di jalan.

### Assessing Data
"""

print(df.info())

"""**Insight:**
- Dari total 35064 entri, beberapa kolom memiliki nilai yang hilang (non-null count yang lebih rendah dari 35064).
PM2.5: Terdapat 382 nilai yang hilang.
PM10: Terdapat 284 nilai yang hilang.
SO2: Terdapat 575 nilai yang hilang.
NO2: Terdapat 1070 nilai yang hilang.
CO: Terdapat 1802 nilai yang hilang.
O3: Terdapat 2107 nilai yang hilang.
Ini menunjukkan bahwa ada kemungkinan untuk melakukan imputasi atau penanganan data hilang sebelum melakukan analisis lebih lanjut.

### Cleaning Data
"""

print(df.isnull().sum())
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
df.drop_duplicates(inplace=True)
print(df.describe())

"""**Insight:**
- Setelah menerapkan metode imputasi median untuk kolom numerik, jumlah nilai hilang yang tersisa bervariasi dari 0 (untuk kolom tahun, bulan, hari, dan jam) hingga beberapa ribu (untuk PM2.5, CO, O3, dan lainnya).
- Analisis Korelasi: Menghitung koefisien korelasi antara polutan dan kondisi cuaca untuk memahami hubungan lebih dalam.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

average_pollutants = df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']].mean()

# Menampilkan hasil rata-rata
print(average_pollutants)

# Visualisasi rata-rata polutan
average_pollutants.plot(kind='bar', color='skyblue')
plt.title('Rata-rata Konsentrasi Polutan di Perkotaan')
plt.ylabel('Konsentrasi Rata-rata (µg/m³)')
plt.xlabel('Polutan')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

"""### Pertanyaan 2:"""

# Menyiapkan data untuk visualisasi
plt.figure(figsize=(14, 7))
sns.lineplot(data=df, x='datetime', y='PM2.5', label='PM2.5', color='blue')
plt.title('Tren PM2.5 Seiring Waktu')
plt.xlabel('Tanggal')
plt.ylabel('Konsentrasi PM2.5 (µg/m³)')
plt.xticks(rotation=45)
plt.grid()
plt.legend()
plt.show()

"""**Insight:**
- Identifikasi Polutan Utama
- Apakah ada tren meningkat atau menurun dalam konsentrasi PM2.5 dari tahun ke tahun? Penurunan konsentrasi dapat menunjukkan keberhasilan kebijakan pengendalian polusi, sementara peningkatan mungkin mengindikasikan masalah baru yang perlu ditangani.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Rata-rata Konsentrasi Polutan di Perkotaan: Diagram batang akan menunjukkan polutan mana yang memiliki konsentrasi rata-rata tertinggi, memungkinkan Anda untuk mengidentifikasi polutan utama yang berkontribusi terhadap buruknya kualitas udara.
- Tren Kualitas Udara: Visualisasi garis pertama akan menunjukkan tren PM2.5 seiring waktu, memungkinkan Anda untuk melihat fluktuasi dan pola musiman.
"""